[versions]
skeleton-library-shared = "0.0.4"
skeleton-library-excel = "0.0.6"

[libraries]
poi-ooxml = { group = "org.apache.poi", name = "poi-ooxml", version = "5.4.1" }
skeleton-library-shared = { group = "kr.skeleton", name = "skeleton-library-shared", version.ref = "skeleton-library-shared" }
